export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css';
import { DevToolsInitializer } from '../components/DevToolsInitializer';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <DevToolsInitializer />
      </body>
    </html>
  )
}
